# Use an official Python runtime as a parent image
FROM python:3.9.6-alpine

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=material_manager.settings.production
# Set the working directory in the container
WORKDIR /usr/src/back_end_material_manager

# Copy the current directory contents into the container at /app
COPY . /back_end_material_manager

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define the command to run your app using CMD which keeps the container running.
CMD ["python", "manage.py", "migrate"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]